### ISSUE TITLE
Private buckets

### ISSUE THREAD

**Issue by sanderpick** [textileio/textile#174]
Private buckets should encrypt files and/or it's directory structure. Perhaps the replicator key can be used for structure, and the read key for the actual files.

**Comment by sanderpick** [comment]
After some more thought, and considering the upcoming `bucket push` refactor, here's what I'm currently thinking:

- A private bucket means,
  - The files are encrypted (AES-GCM) with the thread's a key that can be stored as part of the bucket structure. We could use the thread read key, but then all buckets in this thread would have the same key.
  - The Unixfs DAG of the encrypted files is used to recursively pin the files. We could also encrypt this node and store the resulting root as the HEAD of the bucket, but I'm not sure this buys us anything since the hub can control who has access to see the bucket HEAD.
- `bucket init` will need a new param, `private`, which can be part of the config w/ the CLI, but just gets passed as a new param to the `Init` API, meaning JS APIs can use it too. 
- `bucket push` can stay the same, in fact, the whole user facing API should not really change, since the remote has the encryption key.
- A CLI-based private bucket could actually leverage the locally stored DAG structure (a coming change) used for diffing, and still benefit from de-duplication, since the remote could track the unencrypted files roots hash as well.
- At the thread level, the ACL can be used to determine access to instance (bucket) changes. You would still need the bucket key to decrypt the files.

**Comment by carsonfarmer** [comment]
In the above scenario, the UnixFS DAG would essentially still have 'plaintext' links for the encrypted files, correct? Your comment about maybe not buying much makes sense given the buckets setup, but just wanted to clarify.

So essentially, this is a convenience layer over buckets where, instead of encrypting files locally and pushing these to a public bucket, you push the plaintext file and have it encrypted remotely. The buys you deduplication, and what else (there are other benefits, they just aren't jumping out at me right now)?

**Comment by sanderpick** [comment]
The links could be encrypted too. The problem with encrypting the whole DAG is that in that scenario you wouldn't pin the unencrypted DAG, meaning that pinning recursively becomes manual thing. 

The encryption could happen locally, but not sure there's any benefit to that.

**Comment by sanderpick** [comment]
I should expand the thinking around the remote encryption. There are pros and cons to each approach: 

### Remote encryption

**Pros**
- No API changes. Sharing buckets between org members and/or machines is as normal: An account can `init` an existing bucket without having to deal w/ providing the bucket key
- We can use out existing gateway to render encrypted buckets
- Users don't need to do any kind of key management
- Much faster to develop since the client don't need any extra smarts

**Cons**
- The hub will own the encryption key (from here on I'll call this the _bucket key_)

### Local encryption

**Pros**
- The hub will not own the encryption key (more private)
- Maybe more secure, but this depends on how the user is managing keys

**Cons**
- Sharing buckets between org members and/or machines requires somehow getting the bucket key to the other member / machine w/o using the hub. This could compromise security if not done correctly
- Bucket rendering would have to be client side, meaning a good bit of smarts need to be packed into the JS client
- Users need to manage keys
- Slower to develop

Reading the above sounds like the obvious solution is to do the remote encryption. However, I think ideally we can do both. The local approach is definitely quite powerful for those that want to handle keys, etc. 

This type of bucket could actually be called _private_, and the remote encryption type could be called _encrypted_. Encrypted buckets can be built quickly. It makes sense to get a version of these out ASAP. Then, depending on feedback, we can slot in the full private (local encryption) type. Thought? 

Note: I have some work-in-progress around `bucket push` that uses a local _offline_ blockstore for diffing. This sounds pretty helpful for diffing and de-duplication in a locally encrypted world as well, since you could control sync behavior with a local plaintext tree. Probably doable in browser-land as well.

**Comment by carsonfarmer** [comment]
I like this proposal *a lot*. I think it is the right balance of pros/cons, and provides two useful modes of operation that will fit many different use cases. (I'm also all for getting encrypted buckets out as a product sooner rather than later.) Your naming convention here makes a lot of sense to me so 👍 for _encrypted buckets_ and then later _private buckets_.

Very excited about the offline block store stuff, can't wait to see that. We have a block store implementation in TS/JS already, so hopefully it is reasonable to port that :)

**Comment by jsonsivar** [comment]
@sanderpick @carsonfarmer thanks for writing this up. Since this is for our personal desktop app we are thinking of local encryption and storing unless someone shares folder or file with someone else.

Looking at the existing JS buckets interface, looks like the basic crud operations are there so the other thing that comes to mind is how the sharing would work? I.e., do we get back a public key for buckets that we use on our side and add it to a particular users keychain or is the sharing handled internally with threads and just needs an API exposed for that?

>The files are encrypted (AES-GCM) with the thread's a key that can be stored as part of the bucket structure. We could use the thread read key, but then all buckets in this thread would have the same key.

That could be okay because we could simply use a new thread for each bucket right? I'm assuming this should be consistent with how threads is used outside the bucket use case.  I.e., need a way to encrypt the bucket so that the just users invited to share that bucket can see it.

>The Unixfs DAG of the encrypted files is used to recursively pin the files. We could also encrypt this node and store the resulting root as the HEAD of the bucket, but 
I'm not sure this buys us anything since the hub can control who has access to see the bucket HEAD.

Chatting with the team here at Fleek, we landed at it being okay to have the DAG unencrypted as long as the files and directory names are encrytped (assuming this would be okay since in IPFS you can supply an encrypte text as the link name). Think that's a good middleground which means the structure will be leaked but not folder names or files. Since this is for our personal desktop app, we were thinking of using an embedded threads node for this so your note about the hub controlling who has access to see the bucket head does not apply right?

>bucket init will need a new param, private, which can be part of the config w/ the CLI, but just gets passed as a new param to the Init API, meaning JS APIs can use it too.

Agreed

> bucket push can stay the same, in fact, the whole user facing API should not really change, since the remote has the encryption key.

Even in our case since we are aiming for an embedded node/p2p setup, we can still pass in the key via context right?

> A CLI-based private bucket could actually leverage the locally stored DAG structure (a coming change) used for diffing, and still benefit from de-duplication, since the remote could track the unencrypted files roots hash as well.

How does this work for embedded node? It would also have a locally stored DAG so we get the diffing/de-dup as well right?

> Bucket rendering would have to be client side, meaning a good bit of smarts need to be packed into the JS client

If we use an embedded go-threads client in our app, then it should have the encryption built in just like the remote?

**Comment by sanderpick** [comment]
> Since this is for our personal desktop app we are thinking of local encryption and storing unless someone shares folder or file with someone else.

Okay, that makes sense. But reading below, sounds like you don't want to use `textile`, just `go-threads`? Remember that buckets are not part of `go-threads`, they are a hub concept handling:
- Pinning
- Filecoin archiving

Are you thinking of leveraging threaddb to make your own bucket concept? 

> Looking at the existing JS buckets interface, looks like the basic crud operations are there so the other thing that comes to mind is how the sharing would work? I.e., do we get back a public key for buckets that we use on our side and add it to a particular users keychain or is the sharing handled internally with threads and just needs an API exposed for that?

This will depend on the above question ^.

> > The files are encrypted (AES-GCM) with the thread's a key that can be stored as part of the bucket structure. We could use the thread read key, but then all buckets in this thread would have the same key.
> 
> That could be okay because we could simply use a new thread for each bucket right? I'm assuming this should be consistent with how threads is used outside the bucket use case. I.e., need a way to encrypt the bucket so that the just users invited to share that bucket can see it.

Not necessarily. You can think of a thread like a database. Typically you have more than one entity in a database, and usually more than one collection. Encryption keys are cheap, so it's not a botttleneck of any kind... may as well keep it flexible for other use cases. 

> > The Unixfs DAG of the encrypted files is used to recursively pin the files. We could also encrypt this node and store the resulting root as the HEAD of the bucket, but
> > I'm not sure this buys us anything since the hub can control who has access to see the bucket HEAD.
> 
> Chatted with the team here at Fleek, we landed at it being okay to have the DAG unencrypted as long as the files and directory names are encrypted (assuming this would be okay since in IPFS you can supply an encrypt text as the link name). Think that's a good middle ground which means the structure will be leaked but not folder names or files. Since this is for our personal desktop app, we were thinking of using an embedded threads node for this so your note about the hub controlling who has access to see the bucket head does not apply right?
> > bucket push can stay the same, in fact, the whole user facing API should not really change, since the remote has the encryption key. 
> Even in our case since we are aiming for an embedded node/p2p setup, we can still pass in the key via context right?
> > A CLI-based private bucket could actually leverage the locally stored DAG structure (a coming change) used for diffing, and still benefit from de-duplication, since the remote could track the unencrypted files roots hash as well.
> 
> How does this work for embedded node? It would also have a locally stored DAG so we get the diffing/de-dup as well right?
> 
> > Bucket rendering would have to be client side, meaning a good bit of smarts need to be packed into the JS client
>
> If we use an embedded go-threads client in our app, then it should have the encryption built in just like the remote?

Reading these other questions above, sounds like you're trying to use go-threads to make buckets on your own?

**Comment by jsonsivar** [comment]
Oh I just referred to `go-threads` because I thought that's where the buckets interfaces would be.  I guess I meant `textile` not `go-threads` then in that case. So I think our setup would be using go-threads to have a node running embedded in the app, then textile to do the bucket operations on top of that. But confirm if my thinking is correct there. Basically we want a setup where there are no servers and files are stored locally and only shared with other users if they are explicitly shared and done through Textile's p2p layer (since we don't work with IPFS directly).
