### ISSUE TITLE
tt bucket push shouldn't push the .textile directory

### ISSUE THREAD

**Issue by Stebalien** [textileio/textile#197]
The following command will push the .textile directory along with the rest of the directory. This is likely not what the user wants.

```
> tt bucket push . .
```

**Comment by sanderpick** [comment]
Yep, good eye. The push command is currently in a middle ground between operating like a remote file system (the original implementation), and something more like git (push to sync all). This is because we recently switched to the local config setup, which is driven by CWD.

So, we'll make the final move to the more git-like functionality, which will result in the local config not being a part of the actual UnixFS directory.
