### ISSUE TITLE
Add a buckets `open` method to the api

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile#292]
When building an application there is a common flow required to get the app to use the correct bucket again on startup/recovery/ or initialization.

1. Select the thread where the bucket exists. It seems typically by name here makes sense, but ThreadID maybe for some use-cases. 
2. If that thread doesn't exist, create it.
3. Select the bucket on that thread by name, or select a default one ('buckets' or 'default' or whatever convention we choose for a default bucket).
4. If that bucket doesn't exist create it.
5. Return the threadid and bucket key at the end.

After encoding that exact flow of request, list, sort, if else create, etc into a few examples, I just added it as a helper method to the @textile/buckets lib here,

https://github.com/textileio/js-hub/blob/master/packages/buckets/src/buckets.ts#L93

You can see for inputs it takes,

1. bucket name. doesn't matter if it already exists. but will always return a new one or existing one depending.
2. threadName. optional, otherwise it will just use a default.
3. privacy setting. if the bucket ends up needing to be created, allows the addition of private buckets. same default as api
4. threadid. optional. in my example it would override the threadname in the search for existing. but when creating it, they'd end up the same.

For the  end user it doesn't return the threadId, but from a remote API we'd need it to. Internal to the `open` function it will set the thread header to the resulting threadid for the user, so subsequent calls are correctly scoped. 

cc @sanderpick

**Comment by sanderpick** [comment]
Nice, sounds good to me. 

Can this be distilled down to: _get or create this thread_name/bucket_name combo_ ? 

If so, sounds like a good fit for a couple more User API methods (along w/ `GetThread` and `ListThreads`). 
- `GetOrCreateDB`: Get the thread by name (in the same way as `GetThread`), if not exists, create a new db-thread by that name. If there's already a non-db thread in there, error

Then, we could define a new bucket client method that looks like,
- `GetOrInitBucket`: Now that we have the thread ID, get or init the bucket with name

We can't do the whole flow in the User or Bucket API because there's no way for the service-side of the user api to call the service side of the buckets API (or the other way around) w/o creating a huge amount of spaghetti.

**Comment by sanderpick** [comment]
Eh, actually `GetOrCreateDB` won't work either since the way to create threads is via the thread's client, meaning we'd run into the same service-to-service issue mentioned above.

So, maybe just a new bucket client method `GetOrInitBucket`? That would return the same response as the normal `Init`, plus the thread ID.

**Comment by andrewxhill** [comment]
so based on 

> no way for the service-side of the user api to call the service side of the buckets API 

`GetOrInitBucket` on the client would still wrap up an initial call to `GetOrCreateDB` on the User API, not relying on the service to do it?

**Comment by sanderpick** [comment]
That's what I was originally thinking, but that won't work either for the same reason (see second comment). The best we can do here is to define a nice client method. 

Which gets me thinking, I think a JS buckets lib might find better alignment with the Bucket Library (`buckets/local`), which leverages all the lower level clients (threads, buckets, and users). Check out these methods: https://pkg.go.dev/github.com/textileio/textile/buckets/local?tab=doc#Bucket. Does that look closer to a cross-language spec for a bucket client? 

Some won't make sense in JS because there's no local filesystem (or maybe only conditionally when there is in NodeJS).
