### ISSUE TITLE
[https://slate.host] Archive: `buckets.archive` needs to return useful information for third-party groups.

### ISSUE THREAD

**Issue by jimmylee** [textileio/textile#385]
Right now `buckets.archive` doesn't return anything trackable after its called. Here is what would be useful:

* The JSON Schema of a reliable deal receipt we can use for future queries
* The Deal ID if possible (Probably not possible because it takes forever to make a deal)

This is pretty important, given that Coinbase's Earn campaign will need something like this to track on their end and I want to provide it since `buckets.archive` is the mechanism for both

* One-off storage deal
* Archiving an entire bucket

**Comment by asutula** [comment]
This was implemented in https://github.com/textileio/textile/pull/412. The call to `Archive` can't actually return any information about the underlying deals because the process of creating those deals is very async. But the solution is that you can call `Archives` and get the current and historical archive status which now includes information about underlying deals and their statuses.
