### ISSUE TITLE
Error! App denied net record body: permission denied

### ISSUE THREAD

**Issue by BabycolaYang** [textileio/textile#386]
when I run the command "hub buck push",I got the error below.
`Error! App denied net record body: permission denied`.
What does this mean or what should i do?

**Comment by andrewxhill** [comment]
in case others find this ticket. this error most likely occurs because you are attempting to push a bucket created in an organization but without passing the org name. you can pass the correct org name in two ways,

`hub buck push --org [name]`

alternatively, the CLI is setup to read an environmental variable containing the org name. this is helpful when performing multiple operations and not having to pass the name each time.

```
export HUB_ORG=[name]
hub buck push
```
